#### 1 GET player 

GET http://localhost:3010/players/

### 2 get player by id

GET http://localhost:3010/players/2/

### 3 put player by id

PUT http://localhost:3010/players/3/

Content-Type: application/json

{
  "playerName": "Raju"
}

### 4 MATCH DETAILS BY ID 

GET http://localhost:3010/matches/5/


### 5 math by player Id 

GET http://localhost:3010/players/5/matches/

### 6 player by match id 

GET http://localhost:3010/matches/2/players/

#### 7 player scores 

GET http://localhost:3010/players/5/playerScores/